langauge: c

compiler:
  - gcc
  - clang

script:
  - cd src/my/ && make && cd -
  - cd test/my/ && make && ./testmy && cd -

addons:
  apt:
    packages:
      - cmake
      - libcunit1
      - libcunit1-dev
      - build-essential
